service: knative-demo
description: "Deploying functions from GitLab using Knative"

provider:
  name: triggermesh
  environment:
    FOO: BAR

functions:
  python:
    source: python/handler.py
    description: "python Lambda compatible"
    runtime: https://raw.githubusercontent.com/triggermesh/knative-lambda-runtime/master/python-3.7/runtime.yaml
    buildargs:
      - DIRECTORY=python
      - HANDLER=handler.endpoint
